- name: "Cisco ACI Query Tenant/EPG"
  hosts: all
  gather_facts: no
  connection: local
 
  tasks:
    - name: ACI query all tenant
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        state: query
 
    - name: ACI query all EPG
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        state: query